In [ ]:
#1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

In [4]:
arr1 = np.random.randint(1, 100, (3, 3))
arr1

array([[56, 31, 44],
       [70, 12, 81],
       [91, 96, 96]])

In [5]:
arr1.T ## Interchange rows and columns using transpose()

array([[56, 70, 91],
       [31, 12, 96],
       [44, 81, 96]])

In [ ]:
#2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [6]:
l = [1,2,3,4,5,6,7,8,9,10]
arr2 = np.array(l)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr2.ndim #1dimension

1

In [12]:
arr3= arr2.reshape(2,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr4 =arr2.reshape(5,2)
arr4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [14]:
arr1 = np.random.rand(4,4)
arr1

array([[0.46381809, 0.45705287, 0.16686518, 0.16351097],
       [0.06078847, 0.08665399, 0.40827986, 0.54546341],
       [0.92214383, 0.25155277, 0.51003897, 0.2942337 ],
       [0.02013402, 0.63895613, 0.53416947, 0.02082642]])

In [15]:
arr2 = np.pad(arr1,pad_width =1, mode ="constant", constant_values =0)
print(arr2)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.46381809 0.45705287 0.16686518 0.16351097 0.        ]
 [0.         0.06078847 0.08665399 0.40827986 0.54546341 0.        ]
 [0.         0.92214383 0.25155277 0.51003897 0.2942337  0.        ]
 [0.         0.02013402 0.63895613 0.53416947 0.02082642 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#4.Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [17]:
arr1 = np.arange(10,61,5)
arr1


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [ ]:
#5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [18]:
a = np.array(['python', 'numpy', 'pandas'])
a

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [19]:
np.char.upper(a)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [20]:
np.char.lower(a)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [21]:
np.char.title(a)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [22]:
arr = np.array(['hello', 'world', 'how', 'are', 'you'])

In [23]:
def insert_spaces(word):
  return ' '.join(list(word))

vectorized_insert_spaces = np.vectorize(insert_spaces)
result = vectorized_insert_spaces(arr)
print(result)

['h e l l o' 'w o r l d' 'h o w' 'a r e' 'y o u']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [24]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(3, 5, (3, 3))

In [25]:
arr1

array([[2, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [26]:
arr2

array([[3, 4, 4],
       [4, 4, 4],
       [4, 3, 4]])

In [28]:
np.add(arr1,arr2)

array([[5, 5, 5],
       [5, 6, 5],
       [5, 5, 5]])

In [29]:
np.subtract(arr1,arr2)

array([[-1, -3, -3],
       [-3, -2, -3],
       [-3, -1, -3]])

In [30]:
np.multiply(arr1,arr2)

array([[6, 4, 4],
       [4, 8, 4],
       [4, 6, 4]])

In [31]:
np.divide(arr1,arr2)

array([[0.66666667, 0.25      , 0.25      ],
       [0.25      , 0.5       , 0.25      ],
       [0.25      , 0.66666667, 0.25      ]])

In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [32]:
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [33]:
import numpy as np

def is_prime(n):
  if n <= 1:
    return False
  if n <= 3:
    return True
  if n % 2 == 0 or n % 3 == 0:
    return False
  i = 5
  while i * i <= n:
    if n % i == 0 or n % (i + 2) == 0:
      return False
    i += 6
  return True

# Generate the array of random integers
arr = np.random.randint(0, 1001, 100)

# Find and display prime numbers
prime_numbers = [num for num in arr if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [571, 853, 43, 491, 457, 433, 277, 181, 47, 881, 499, 467, 593, 13, 653, 881]


In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [36]:
import numpy as np

# Generate random daily temperatures for a month (let's assume 30 days)
daily_temperatures = np.random.randint(20, 35, 30)

# Reshape the array into weeks (assuming weeks start on Monday and we discard extra days)
num_weeks = daily_temperatures.size // 7  # Calculate how many full weeks we have
weekly_temperatures = daily_temperatures[:num_weeks * 7].reshape(num_weeks, 7)  # Reshape, discarding extra days

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Weekly average temperatures:")
for i, avg in enumerate(weekly_averages):
    print(f"Week {i+1}: {avg:.2f}")

Weekly average temperatures:
Week 1: 23.29
Week 2: 28.57
Week 3: 27.14
Week 4: 29.14
